PROFESSOR,

I COMPLETED THIS ASSIGNMENT WELL BEFORE THE DEADLINE. OUT OF PURE STUPIDITY, I FORGOT TO UPLOAD EVERYTHING TO GITHUB UNTIL EARLIER THIS EVENING, SIMPLY BECAUSE I FORGOT TO UPLOAD WHEN I FINISHED.
THIS IS WHY MY SECTION 6 EVIDENCE IS PAST MIDNIGHT. I APOLOGIZE PROFUSELY, AND I HOPE THAT THE EVIDENCE BEING AFTER MIDNIGHT (by 19 seconds) IS NOT A HUGE DEAL. PLEASE CONTACT ME AT MY EMAIL
(antakidx@mail.uc.edu) IF YOU WOULD LIKE ADDITIONAL INFORMATION ON MY FAILURE TO UPLOAD THE EVIDENCE BEFORE MIDNIGHT.

KIND REGARDS,
DOMINIC ANTAKI.
